# Generated by Django 5.0.5 on 2024-06-08 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_addressfield_delete_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addressfield',
            new_name='Address',
        ),
    ]
