# Generated by Django 5.0.5 on 2024-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_cart_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_placed',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('packed', 'Packed'), ('One_the_way', 'On The WAY'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
